"""Supervisor — LangGraph StateGraph orchestrating the full Nexus pipeline.

Pipeline flow:
  research → kb_build → analysis → factcheck → [HITL interrupt] → report → END

Checkpointing:
  compiled_graph   — MemorySaver for sync flows (FastAPI in-process state).
  async_graph_ctx  — AsyncRedisSaver for Celery async flows (cross-process state
                     stored in Redis so worker and FastAPI share the same snapshot).
                     Falls back to compiled_graph if Redis is unavailable.
  eval_graph       — MemorySaver, no HITL interrupt (golden dataset evaluation).
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import datetime, timezone

import structlog
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph

from nexus.agents.analysis_agent import analysis_node
from nexus.agents.factcheck_agent import factcheck_node
from nexus.agents.kb_builder_agent import kb_builder_node
from nexus.agents.research_agent import research_node
from nexus.schemas.config import Settings
from nexus.schemas.state import NexusState, PipelineStage

logger = structlog.stdlib.get_logger(__name__)


# ---------------------------------------------------------------------------
# HITL gate node
# ---------------------------------------------------------------------------

async def hitl_gate_node(state: NexusState) -> dict:
    """Mark the pipeline as awaiting human review.

    This node runs AFTER the interrupt resumes, meaning a human has
    approved the results. It simply transitions the stage forward.
    """
    log = logger.bind(run_id=state["run_id"])
    log.info("hitl_gate.approved")
    return {
        "stage": PipelineStage.HITL_REVIEW,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Report generation node
# ---------------------------------------------------------------------------

async def report_node(state: NexusState) -> dict:
    """Compile the final markdown report from analysis + fact-check results."""
    run_id = state["run_id"]
    query = state["query"]
    analysis = state.get("analysis_summary", "")
    fact_checks = state.get("fact_check_results", [])
    log = logger.bind(run_id=run_id)
    log.info("report.generating")

    # Build markdown report
    sections = [
        f"# Competitive Intelligence Report",
        f"",
        f"**Query:** {query}",
        f"**Run ID:** {run_id}",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        f"",
        f"---",
        f"",
        f"## Analysis",
        f"",
        analysis or "_No analysis available._",
        f"",
        f"---",
        f"",
        f"## Fact-Check Results",
        f"",
    ]

    if fact_checks:
        for line in fact_checks:
            sections.append(f"- {line}")
    else:
        sections.append("_No fact-check results available._")

    sections.extend([
        f"",
        f"---",
        f"",
        f"_Report generated by Nexus CI Pipeline_",
    ])

    report_md = "\n".join(sections)
    log.info("report.complete", report_length=len(report_md))

    return {
        "stage": PipelineStage.COMPLETE,
        "report_markdown": report_md,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Routing logic
# ---------------------------------------------------------------------------

def _route_after_node(state: NexusState) -> str:
    """Supervisor routing: check if any node set FAILED, otherwise continue."""
    stage = state.get("stage", PipelineStage.RECEIVED)
    if stage == PipelineStage.FAILED:
        return END
    return "continue"


# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------

def build_graph() -> StateGraph:
    """Construct the Nexus pipeline StateGraph (uncompiled).

    Returns:
        An uncompiled StateGraph ready for .compile().
    """
    graph = StateGraph(NexusState)

    # Add nodes
    graph.add_node("research", research_node)
    graph.add_node("kb_build", kb_builder_node)
    graph.add_node("analysis", analysis_node)
    graph.add_node("factcheck", factcheck_node)
    graph.add_node("hitl_gate", hitl_gate_node)
    graph.add_node("report", report_node)

    # Set entry point
    graph.set_entry_point("research")

    # research → kb_build (or END on failure)
    graph.add_conditional_edges(
        "research",
        _route_after_node,
        {"continue": "kb_build", END: END},
    )

    # kb_build → analysis (or END on failure)
    graph.add_conditional_edges(
        "kb_build",
        _route_after_node,
        {"continue": "analysis", END: END},
    )

    # analysis → factcheck (or END on failure)
    graph.add_conditional_edges(
        "analysis",
        _route_after_node,
        {"continue": "factcheck", END: END},
    )

    # factcheck → hitl_gate (or END on failure)
    graph.add_conditional_edges(
        "factcheck",
        _route_after_node,
        {"continue": "hitl_gate", END: END},
    )

    # hitl_gate → report
    graph.add_edge("hitl_gate", "report")

    # report → END
    graph.add_edge("report", END)

    return graph


def compile_graph(checkpointer=None) -> object:
    """Compile with HITL interrupt at 'hitl_gate'.

    Returns:
        A compiled LangGraph ready for .ainvoke() or .astream().
    """
    if checkpointer is None:
        checkpointer = MemorySaver()

    graph = build_graph()
    compiled = graph.compile(
        checkpointer=checkpointer,
        interrupt_before=["hitl_gate"],
    )
    logger.info("supervisor.graph_compiled", interrupt_at="hitl_gate")
    return compiled


def compile_eval_graph() -> object:
    """Compile WITHOUT HITL interrupt — runs to COMPLETE automatically.

    Used by the golden dataset evaluator so each query completes without
    human intervention. Uses MemorySaver (state is ephemeral, eval only).
    """
    graph = build_graph()
    compiled = graph.compile(checkpointer=MemorySaver())
    logger.info("supervisor.eval_graph_compiled")
    return compiled


# Module-level singletons — MemorySaver for sync flows (in-process state only)
compiled_graph = compile_graph()
eval_graph = compile_eval_graph()  # No HITL — for golden dataset evaluation


@asynccontextmanager
async def async_graph_ctx():
    """Async context manager providing a compiled graph backed by AsyncRedisSaver.

    Why this exists: Celery workers and FastAPI run in separate OS processes.
    MemorySaver state is per-process, so a worker writing state can't be read
    by FastAPI. AsyncRedisSaver uses Redis as shared storage, solving this.
    AsyncRedisSaver (not RedisSaver) is required because LangGraph's ainvoke()
    calls aget_tuple() — the sync RedisSaver raises NotImplementedError there.

    Falls back to compiled_graph (MemorySaver) if Redis is unavailable, which
    means async Celery pipelines won't work but sync pipelines still will.

    Why the setup is split from the yield:
    asynccontextmanager only allows ONE yield. If the body (Celery task) raises
    an exception, it is thrown back into the generator AT the yield point. If the
    yield is inside a try/except, catching that thrown exception and yielding again
    causes RuntimeError('generator didn't stop after athrow()'). The fix is to
    complete setup BEFORE the yield, so the except only handles setup failures.
    """
    settings = Settings()

    # Phase 1: try to open an AsyncRedisSaver connection.
    # If this fails we fall back immediately — only ONE yield follows.
    saver_cm = None
    try:
        from langgraph.checkpoint.redis.aio import AsyncRedisSaver  # noqa: PLC0415

        saver_cm = AsyncRedisSaver.from_conn_string(settings.redis_url)
        saver = await saver_cm.__aenter__()
        await saver.setup()
    except Exception as exc:
        logger.warning("supervisor.async_redis_fallback", error=str(exc))
        saver_cm = None

    # Phase 2: yield. Exactly one path yields — no double-yield possible.
    if saver_cm is None:
        yield compiled_graph  # MemorySaver fallback
        return

    try:
        yield compile_graph(saver)
    except BaseException as exc:
        # Body raised — close the Redis connection with the exception info, then re-raise.
        await saver_cm.__aexit__(type(exc), exc, exc.__traceback__)
        raise
    else:
        await saver_cm.__aexit__(None, None, None)
